// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-OysvLhtohV4cJeJQvWeV7nYiql2LfHk',
    appId: '1:244143438224:web:7f8b27de4290e1002d5b15',
    messagingSenderId: '244143438224',
    projectId: 'movies-db-7d7b2',
    authDomain: 'movies-db-7d7b2.firebaseapp.com',
    databaseURL: 'https://movies-db-7d7b2-default-rtdb.firebaseio.com',
    storageBucket: 'movies-db-7d7b2.appspot.com',
    measurementId: 'G-V90GQ4Y62X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCPfnIGzRp6uDXl0gA9R3ZDCLK6BrKbU',
    appId: '1:244143438224:android:6376bd4e3a7cdcb92d5b15',
    messagingSenderId: '244143438224',
    projectId: 'movies-db-7d7b2',
    databaseURL: 'https://movies-db-7d7b2-default-rtdb.firebaseio.com',
    storageBucket: 'movies-db-7d7b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_yd9v8gbxNXGvH0uwMk2VcjpkMOgpFI',
    appId: '1:244143438224:ios:1615c289dc09ab042d5b15',
    messagingSenderId: '244143438224',
    projectId: 'movies-db-7d7b2',
    databaseURL: 'https://movies-db-7d7b2-default-rtdb.firebaseio.com',
    storageBucket: 'movies-db-7d7b2.appspot.com',
    androidClientId: '244143438224-oubvq9g12j6hf7tjfkf04md4obnctapv.apps.googleusercontent.com',
    iosClientId: '244143438224-4l62ib36jjrog2apfbqeun07f4up62qb.apps.googleusercontent.com',
    iosBundleId: 'com.bolanader5.MoviesDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_yd9v8gbxNXGvH0uwMk2VcjpkMOgpFI',
    appId: '1:244143438224:ios:1615c289dc09ab042d5b15',
    messagingSenderId: '244143438224',
    projectId: 'movies-db-7d7b2',
    databaseURL: 'https://movies-db-7d7b2-default-rtdb.firebaseio.com',
    storageBucket: 'movies-db-7d7b2.appspot.com',
    androidClientId: '244143438224-oubvq9g12j6hf7tjfkf04md4obnctapv.apps.googleusercontent.com',
    iosClientId: '244143438224-4l62ib36jjrog2apfbqeun07f4up62qb.apps.googleusercontent.com',
    iosBundleId: 'com.bolanader5.MoviesDb',
  );
}
